ospi:
  image: stefanscherer/ospi:2.1.7
  restart: always
  privileged: true
  volumes:
    - '/dev/mem:/dev/mem'
    - './data/logs:/logs'
    - './data/nvm.dat:/nvm.dat'
    - './data/stns.dat:/stns.dat'
  expose:
    - 8080
  ports:
    - 8080:8080
