btsync:
  build: btsync
  restart: always
  volumes:
    - '/mnt/Public/share:/mnt/mounted_folders/share'
    - './btsync/sync:/mnt/sync'
  expose:
    - 8888
    - 55555
  ports:
    - 8888:8888
    - 55555:55555

daapd:
  build: forked-daapd
  restart: always
  volumes:
    - '/mnt/Public:/media'
    - './forked-daapd/cache:/cache'
    - './forked-daapd/remote:/remote'
  net: host
  expose:
    - 3689
  ports:
    - 3689:3689

portainer:
  image: hypriot/rpi-portainer
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './portainer:/data'
  expose:
    - 9000
  ports:
    - 80:9000

samba:
  image: dastrasmue/rpi-samba:v3
  hostname: 'pi4'
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './portainer:/data'
  ports:
    - 137:137/udp
    - 138:138/udp
    - 139:139
    - 445:445
    - 445:445/udp
  volumes:
    - './samba:/share/stick'
  command: -s "Public:/share/stick:rw:"
